### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by yalov**
Localization support and Russian localization.

Added # to the names (TT19, etc) for placing around the stock TT18 clamp in the VAB.

### CODE REVIEW

**Comment by yalov** [comment]
@Galileo88  What are you doing there 428d7d0 ? Should I duplicate changes ?

**Comment by yalov** [comment]
@Galileo88 Why did you duplicate all files in FASA/ to GameData/FASA/ ?

**Comment by yalov** [comment]
Can you delete FASA/ and leave GameData/FASA/ ?

**Comment by Galileo88** [comment]
I deleted FASA and left GameData/Fasa. Not sure how that happened to be honest. I assume it was drunken "modding". I know i moved everything in GameData to make it easier to package up for release, but why i left the original FASA folder, I dont know.

**Comment by yalov** [comment]
Updated PR

**Pull request merged**
